dependencies:
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
networks:
  goerli:
    eth_usd_price_feed: '0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e'
    verify: True
  mainnet-fork-dev:
    eth_usd_price_feed: '0xaEA2808407B7319A31A383B6F8B60f04BCa23cE2'
    verify: False
  development:
    verify: False
  ganache-local:
    verify: False
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}